package me.nentify.titles.stats;

public enum Stat {
    BLOCKS_BROKEN,
    ONLINE_TIME,
    CHAT_MESSAGES,
    AGGRESSIVE_MOBS_KILLED,
    ENGINEER,
    BLOCKS_CHISELLED,
    OC_INTERACTIONS,
    BLOCKS_PLACED,
    FARM_INTERACTIONS,
    FISH_CAUGHT
}
